### ISSUE TITLE
Day of the week labels cannot be changed

### ISSUE THREAD

**Issue by yukkes** [year-calendar/v-year-calendar#1]
How do I change the day and month labels?
Example: `["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]`

And in my opinion, I thought it would be nice to have a code sample that added to `dataSource` when I clicked on the calendar.

**Comment by rusicsemenov** [comment]
Hi, you can change in dist folder 
`v-year-calendar>dist>v-year-calendar.js`

row: `headerCell.textContent = Calendar.locales[this.options.language].daysMin[d];` 
to: `headerCell.textContent = Calendar.locales[this.options.language].daysShort[d];`

and calendar show `Sun  Mon ....` but you need change style to.
![Screenshot_75](https://user-images.githubusercontent.com/20163858/76351221-20484f80-631e-11ea-9734-50bf520456f8.png)

**Comment by yukkes** [comment]
Thank you for your reply. I will try the code you provided.
I thought that sample code should be fulfilled.
