### ISSUE TITLE
disables array of date

### ISSUE THREAD

**Issue by syafieqq** [year-calendar/v-year-calendar#2]
hi, got a problem, to disable list of date, can someone help me which methods should i use, and can provide example?, here is currently what i'm doing 

:disabled-days = "holiday"

holiday:['2020-05-05', '2020-04-04', '2020-03-03', '2020-03-02', '2020-01-01']

basically this 5 dates should be disable, thanks. :)

**Comment by rusicsemenov** [comment]
Hi you can yse `:disabledDays="[new Date(2020, 2, 12)]"` 

or `:disabledDays="holiday"` and 

```
holiday: [
    new Date(2020, 4, 5), // moth from 0
    new Date("2020-05-04 00:00:00"), // time necessarily 
    new Date("2020-03-02 00:00:00"), 
    new Date("2020-01-01 00:00:00")
]
```

**Comment by syafieqq** [comment]
ok, thanks @rusicsemenov
